# Site settings.
title: るまライブラリ
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  てすてす．ういーん
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lumc_
github_username:  LumaKernel
disqus: 
  # short_name: 
lang: ja
author: luma

# Build settings
markdown: redcarpet
theme: minima
plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
