# Site settings.
title: るまライブラリ
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  ぼくが競プロで使うライブラリです．
baseurl: "/ecasdqina" # the subpath of your site, e.g. /blog
url: "https://lumakernel.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lumc_
github_username:  LumaKernel
disqus: 
  shortname: ecas
lang: ja
author: luma

# Build settings
markdown: kramdown
# https://kramdown.gettalong.org/syntax_highlighter/rouge.html
# rougeを切るのがわかりずらかった
highlighter: true
theme: minima
plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
